services:
  irs-simulation:
    image: ghcr.io/collaborativeroboticslab/industrial-robots-and-systems-warehouse:jazzy
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related

  omron_handsolo:
    container_name: omron_handsolo
    image: ghcr.io/collaborativeroboticslab/omron_handsolo:jazzy
    command: ros2 launch handsolo_ros handsolo.launch.py tm_use_simulation:=false use_arm:=true use_base:=true use_moveit:=true use_nav2:=true use_rviz:=false
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related

  omron-workspace:
    image: ghcr.io/collaborativeroboticslab/omron-workspace:jazzy
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=0
      - NO_AT_BRIDGE=1
      - QT_X11_NO_MITSHM=1
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw                    # GUI related
      - ./workspace/workspace:/workspace:rw
      - ./workspace/code-server/config:/root/.config/code-server:rw
      - ./workspace/code-server/data:/root/.local/share/code-server:rw

  irs-openplc-runtime:
    container_name: openplc-runtime
    image: ghcr.io/autonomy-logic/openplc-runtime:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    ports:
      - 8443:8443
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
    volumes:
      - openplc-runtime-data:/var/run/runtime

  irs-openplc-editor:
    image: ghcr.io/collaborativeroboticslab/industrial-robots-and-systems-openplc-editor:jazzy
    ipc: host
    environment:
      - DISPLAY
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./openplc-editor/data:/editor_data:rw
      
volumes:
  openplc-runtime-data: